name: nexfile
description: A new Flutter project.
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.0.0
  network_info_plus: ^3.0.2
  wakelock: ^0.6.2
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.1
  mime: ^1.0.4
  shelf: ^1.4.0
  connectivity_plus: ^3.0.4
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - interface/index.html
    - interface/bootstrap.min.css